<a href="https://colab.research.google.com/github/raghav1674/MLOPS/blob/master/01_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


In [2]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [3]:
df.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

In [4]:
df.corr()

longitude  latitude  ...  median_income  median_house_value
longitude            1.000000 -0.925208  ...      -0.015485           -0.044982
latitude            -0.925208  1.000000  ...      -0.080303           -0.144917
housing_median_age  -0.114250  0.016454  ...      -0.115932            0.106758
total_rooms          0.047010 -0.038773  ...       0.195383            0.130991
total_bedrooms       0.071802 -0.069373  ...      -0.013495            0.045783
population           0.101674 -0.111261  ...      -0.000638           -0.027850
households           0.059628 -0.074902  ...       0.007644            0.061031
median_income       -0.015485 -0.080303  ...       1.000000            0.691871
median_house_value  -0.044982 -0.144917  ...       0.691871            1.000000

[9 rows x 9 columns]

In [80]:

X = df[list(df.columns[2:-1])]

list(df.columns[:-1])

['longitude',
 'latitude',
 'housing_median_age',
 'total_rooms',
 'total_bedrooms',
 'population',
 'households',
 'median_income']

In [150]:
# X=X.drop(labels="population",axis=1)
X=X.drop(labels="housing_median_age",axis=1)
X

total_rooms  households  median_income
0           5612.0       472.0         1.4936
1           7650.0       463.0         1.8200
2            720.0       117.0         1.6509
3           1501.0       226.0         3.1917
4           1454.0       262.0         1.9250
...            ...         ...            ...
16995       2217.0       369.0         2.3571
16996       2349.0       465.0         2.5179
16997       2677.0       456.0         3.0313
16998       2672.0       478.0         1.9797
16999       1820.0       270.0         3.0147

[17000 rows x 3 columns]

In [151]:
Y=df.iloc[:,-1]

In [152]:
Y

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...   
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

In [153]:
model = LinearRegression()
model.fit(X,Y)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [154]:
model.coef_

array([-2.45499592e+01,  1.44523173e+02,  4.73113183e+04])

In [155]:
model.intercept_

16027.380649182567

In [156]:
df_test = pd.read_csv("/content/sample_data/california_housing_test.csv")

In [157]:
X_train =  df_test[list(df_test.columns[2:-1])]
X_train=X_train.drop(labels="total_bedrooms",axis=1)
X_train=X_train.drop(labels="population",axis=1)
X_train=X_train.drop(labels="housing_median_age",axis=1)

In [158]:
X_train

total_rooms  households  median_income
0          3885.0       606.0         6.6085
1          1510.0       277.0         3.5990
2          3589.0       495.0         5.7934
3            67.0        11.0         6.1359
4          1241.0       237.0         2.9375
...           ...         ...            ...
2995       1450.0       607.0         1.1790
2996       5257.0      1036.0         3.3906
2997        956.0       220.0         2.2895
2998         96.0        14.0         3.2708
2999       1765.0       260.0         8.5608

[3000 rows x 3 columns]

In [159]:
Y_train = df_test.iloc[:,-1]

In [160]:
pred = model.predict(X_train)

In [161]:
pred 

array([320888.67921689, 189263.29583887, 273549.93934913, ...,
       132671.98104272, 170439.76885945, 415295.46139186])

In [162]:
Y_train

0       344700.0
1       176500.0
2       270500.0
3       330000.0
4        81700.0
          ...   
2995    225000.0
2996    237200.0
2997     62000.0
2998    162500.0
2999    500001.0
Name: median_house_value, Length: 3000, dtype: float64

In [163]:
from sklearn.metrics import mean_absolute_error

In [164]:
error = mean_absolute_error(Y_train,pred)

In [165]:
print(error)

60239.54419727743


In [166]:
from sklearn.metrics import r2_score

In [167]:
r2_score(Y_train,pred)

0.4726162121063662

In [168]:
test =X_train.values[90]

In [169]:
model.predict([test])

array([167863.69792049])

In [170]:
Y_train[90]

141700.0